### ISSUE TITLE
Code origin

### ISSUE THREAD

**Issue by faroit** [naetherm/racoonengine#1]
Most of the code seems to originate from https://github.com/WarzesProject/Micro3DRPG

Is this a fork? If yes the original code ownership is not visible anymore and should be noted.

@warzes

**Comment by naetherm** [comment]
Not really, 
this started as a new implementation around another project [0] as some sort of kick off, but in a local branch I've already replaced everything related to it. Will add a note in the remote branches.

[0] https://github.com/cofenberg/unrimp

**Comment by faroit** [comment]
i don't think that is sufficient. 

E.g. here is a comparison of two files: 

https://github.com/naetherm/racoonengine/blob/develop/Engine/Source/Base/RERenderer/Public/RERenderer/IRenderer.h

and 

https://github.com/cofenberg/unrimp/blob/master/Source/Renderer/Public/IRenderer.h

reveal that they are largely identical except for the header and some variable names. Without correct attribution this is a copyright issue

**Comment by naetherm** [comment]
> i don't think that is sufficient.
Yes, just made a quick note in the README.md this morning and currently working on reintegration those comments on this branch. That's also the reason the issue is not closed yet.
